// <auto-generated />
using GithubCommitsViewer.Application.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GithubCommitsViewer.Application.Migrations
{
    [DbContext(typeof(GithubCommitsViewerContext))]
    partial class GithubCommitsViewerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("githubcommitsviewer")
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GithubCommitsViewer.Application.Entities.Commit", b =>
                {
                    b.Property<string>("Sha")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CommitterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepositoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepositoryOwner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Sha");

                    b.ToTable("Commits", "githubcommitsviewer");
                });
#pragma warning restore 612, 618
        }
    }
}
